config/routes.rb
Rails.application.routes.draw do
  get 'newsletters/:id/deliver' , to: 'newsletters#deliver'
  resources :newsletters do
    member { post :deliver }
  end
  resources :subscribers
  get 'subscribers/show' , to:'subscribers#show'
  get '/' , to:'subscribers#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  def self.deliver(id)
    find(id).update
    Subscriber.find_each do |subs|
      SubscriptionMailer.send_email(subs,find(id)).deliver_later
    end
  end

  def update
    update_attribute(:delivered_at, Time.zone.now)
  end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, uniqueness: true
  validates_format_of :email, with: /\A([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  require 'date'
  def deliver
    if (params[:date][:schedule]).present?
      schedule = DateTime.parse(params[:date][:schedule]).in_time_zone
    else
      schedule = 5.minutes.from_now
    end
    Newsletter.delay(queue: "newsletter", priority: 20, run_at: schedule).deliver(params[:id])
    redirect_to newsletters_url, notice: "Delivered newsletter."
  end
  def index
    @newsletters = Newsletter.all
  end

  def show
    @newsletter = Newsletter.find(params[:id])
  end

  def new
    @newsletter = Newsletter.new
  end
  def create
    @newsletter = Newsletter.new(newsletter_params)
    if @newsletter.save
      redirect_to @newsletter, notice: "Successfully created newsletter."
    else
      render :new
    end
  end

  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  def update
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.update_attributes(newsletter_params)
      redirect_to @newsletter, notice: "Successfully updated newsletter."
    else
      render :edit
    end
  end

  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy
    redirect_to newsletters_url, notice: "Successfully destroyed newsletter."
  end
  private
    def newsletter_params
      params.require(:newsletter).permit(:subject,:body)
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscriber = Subscriber.all
  end
  def new
    @subscriber = Subscriber.new
  end
  def show
    @subscriber = Subscriber.all
    @subscriber.each do |subs|
      SubscriptionMailer.send_email(subs.email,"rails").deliver_later!(wait: 1.hour)
    end
  end
  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      flash[:success] = "Thank you for subscribing!"
      redirect_to(:action => 'new')
    else
      render('new')
    end
  end

  private
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nss</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-wrapper">

     <div class="site-wrapper-inner">

       <div class="cover-container">

         <div class="masthead clearfix">
           <div class="inner">
             <h3 class="masthead-brand">Newsletter</h3>
             <nav class="nav nav-masthead">
               <%= link_to 'Home' , new_subscriber_url , class: 'nav-link active' %>
               <%= link_to 'Admin', newsletters_path, class: 'nav-link'  %>
             </nav>
           </div>
         </div>

         <div class="inner cover">
           <%= yield %>
         </div>

         <div class="mastfoot">
           <div class="inner">
             <p> © 2017 Newsletter App.</p>
           </div>
         </div>

       </div>

     </div>

   </div>

  </body>
</html>

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>
      <ul>
      <% @newsletter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<div class="content-top">
  <div class="row">
    <div class="col-md-12">
      List of Newsletters
    </div>
  </div>
</div>
<div class="add-newsletter">
  <%= link_to "New Newsletter", new_newsletter_path ,class: 'btn btn-default' %>
</div>
<div id="flash">
  <% flash.each do |key, value| %>
      <div class="alert alert-success flash <%= key %>"><%= value %></div>
  <% end %>
</div>
<div class="row">
  <% @newsletters.each do |newsletter| %>
    <div class="col-sm-6">
    <div class="card" style="width: 20rem;">
      <% if newsletter.delivered_at.present? %>
        Delivered on <%= newsletter.delivered_at.strftime("%B %d, %Y at %I:%M:%S") %><br />
      <% end %>
      <div class="card-block">

        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-6">Subject</div>
              <div class="col-md-6"><%= newsletter.subject %></div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-6">Body</div>
              <div class="col-md-6"><%= truncate(newsletter.body, :length => 30) %></div>
            </div>
          </div>
          <%= form_tag("/newsletters/#{newsletter.id}/deliver", method: "post") do %>
            <div class="col-md-12" style="margin-left: 5%;">
                <p>Schedule</p>
                <%= datetime_local_field(:date,:schedule,'class'=> 'datepicker' ) %>
            </div>
            </div>
            <br>
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-6">
                  <%= link_to "View", newsletter, class: 'btn btn-default' %>
                </div>
                <div class="col-md-6">
                  <%= submit_tag("send", class: 'btn btn-success') %>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @newsletter.subject %>
</p>
<p>
  <b>body:</b>
  <%= @newsletter.body %>
</p>
<p>
  <b>Delivered at:</b>
  <%= @newsletter.delivered_at %>
</p>


<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>

app/views/subscribers/index.html.erb
<% @subscriber.each do |subs| %>
  <%= subs.email %><br/>
<% end %>

app/views/subscribers/new.html.erb
<section class="home-newsletter">
<div class="container">
  <div class="row">
    <div class="col-sm-12">
    	<div class="single">
        <i class="fa fa-paper-plane"></i>
    		<h2>Subscribe to our Newsletter</h2>
        <%= form_for @subscriber, url: {action: "create"}, html: {class: "subscribe"} do |f| %>
          <% if @subscriber.errors.any? %>
            <% @subscriber.errors.full_messages.each do |message| %>
              <div class="alert alert-danger" role="alert">
                <%= message %>
              </div>
            <% end %>
          <% end %>
          <div id="flash">
            <% flash.each do |key, value| %>
                <div class="alert alert-success flash <%= key %>"><%= value %></div>
            <% end %>
          </div>
          <div class="input-group">
            <%= f.text_field :email, class: 'form-control',placeholder: 'Enter your email' %>
            <span class="input-group-btn">
              <%= f.submit "Subscribe", class: 'btn btn-theme' %>
            </span>
          </div>
        <% end %>
    	</div>
    </div>
  </div>
</div>
</section>

app/views/subscribers/show.html.erb
<% @subscriber.each do |subs| %>
  <%= subs.email %><br/>
<% end %>